name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.1

      - name: Helm Lint
        run: helm lint ./charts/*

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0

      - name: Run chart-testing (install)
        run: helm install --generate-name ./charts/*